@startuml projIncConc_usecase

left to right direction

actor Cliente as Cl
actor Transportadora as Tr

package Fábrica_de_concreto {
  usecase "Preencher ordem de pedido" as UC1
  usecase "Escalonar ordem" as UC2
  usecase "Enviar ordem para produção" as UC3
  usecase "Solicitar materiais" as UC4
  usecase "Entregar materiais" as UC5
  usecase "Executar pedido" as UC6
  usecase "Controlar fabricação" as UC7
  usecase "Misturar componentes" as UC8
  usecase "Emitir ordem de compra de produtos" as UC9
  usecase "Verificar recebimento" as UC10
  usecase "Entregar produto" as UC11
  usecase "Efetuar pagamento" as UC12
}

Cl -- UC1
UC2 -- Departamento_vendas
UC3 -- Departamento_vendas
UC4 -- Encarregado_produção
UC5 -- Encarregado_almoxarifado
UC6 -- Encarregado_produção
UC7 -- Operador_maquinas
UC8 -- Operarios
UC9 -- Encarregado_produção
UC10 -- Departamento_recebimentos_distribuicao
Cl -- UC12
Tr -- UC11
UC12 --> Departamento_financeiro
UC2 ..> UC1 : <<Include>>
UC3 ..> UC2 : <<Include>>
UC6 ..> UC5 : <<Include>>
UC5 ..> UC4 : <<Include>>
UC7 ..> UC6 : <<Include>>
UC8 ..> UC7 : <<Include>>
UC10 ..> UC9 : <<Include>>
UC11 ..> UC6 : <<Include>>
UC12 ..> UC11 : <<Include>>

@enduml