@startuml projIncConc_class

class Cliente {
  nome
  endereco
  telefone
}

class OrdemDePedido {
  tipoConcreto
  quantidade
  status
  dataPedido
  dataEntrega
}

class Transportadora {
  nome
  endereco
  telefone
}

class DepartamentoVendas {
  nome
  responsavel
  ordensDePedido
}

class Encarregado {
  nome
  cargo
}

class DepartamentoCompras {
  nome
  responsavel
  ordensDeCompra
}

class OperadorMaquinas {
  nome
  maquinas
}

class DepartamentoRecebimentos {
  nome
  responsavel
  produtosRecebidos
}

class Operario {
  nome
  cargo
  pagamentos
}

class Planta {
  tipo
  equipamentos
  armazenagens
}

class Produto {
  nome
  estoque
  comprasMateriaPrima
}

class CompraMateriaPrima {
  produto
  quantidade
}

Cliente "1" -- "*" OrdemDePedido : realiza
OrdemDePedido "1" -- "1" Transportadora : entrega
DepartamentoVendas "1" -- "*" OrdemDePedido : escalona
DepartamentoVendas "1" -- "1" Encarregado : envia para
DepartamentoCompras "1" -- "*" OrdemDeCompra : realiza
DepartamentoCompras "1" -- "1" Encarregado : envia pedido
OperadorMaquinas "1" -- "*" Maquina : utiliza
DepartamentoRecebimentos "1" -- "*" Produto : recebe
Cliente "1" -- "1" Pagamento : efetua
Planta "1" -- "*" Equipamento : possui
Planta "1" -- "*" Armazenagem : possui
Produto "1" -- "*" CompraMateriaPrima : contem

@enduml